/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ApplicationToInstall model module.
* @module model/ApplicationToInstall
* @version 1.0
*/
export default class ApplicationToInstall {
    /**
    * Constructs a new <code>ApplicationToInstall</code>.
    * @alias module:model/ApplicationToInstall
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ApplicationToInstall</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApplicationToInstall} obj Optional instance to populate.
    * @return {module:model/ApplicationToInstall} The populated <code>ApplicationToInstall</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationToInstall();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
        }
        return obj;
    }

    /**
    * Id of application
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * Application name
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Description of the application
    * @member {String} description
    */
    'description' = undefined;
    /**
    * href to icon of the application - optional
    * @member {String} icon
    */
    'icon' = undefined;




}
