/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationToInstall from './ApplicationToInstall';
import Limits from './Limits';

/**
* The Body model module.
* @module model/Body
* @version 1.0
*/
export default class Body {
    /**
    * Constructs a new <code>Body</code>.
    * @alias module:model/Body
    * @class
    * @param name {String} 
    * @param projectId {Number} Id of project where container should be created
    * @param templateId {Number} 
    * @param applicationsToInstall {Array.<module:model/ApplicationToInstall>} 
    * @param connectToInternet {Boolean} 
    * @param limits {module:model/Limits} 
    */

    constructor(name, projectId, templateId, applicationsToInstall, connectToInternet, limits) {
        
        
        this['name'] = name;
        this['projectId'] = projectId;
        this['templateId'] = templateId;
        this['applicationsToInstall'] = applicationsToInstall;
        this['connectToInternet'] = connectToInternet;
        this['limits'] = limits;
        
    }

    /**
    * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body} obj Optional instance to populate.
    * @return {module:model/Body} The populated <code>Body</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'Number');
            }
            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'Number');
            }
            if (data.hasOwnProperty('applicationsToInstall')) {
                obj['applicationsToInstall'] = ApiClient.convertToType(data['applicationsToInstall'], [ApplicationToInstall]);
            }
            if (data.hasOwnProperty('connectToInternet')) {
                obj['connectToInternet'] = ApiClient.convertToType(data['connectToInternet'], 'Boolean');
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = Limits.constructFromObject(data['limits']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Id of project where container should be created
    * @member {Number} projectId
    */
    'projectId' = undefined;
    /**
    * @member {Number} templateId
    */
    'templateId' = undefined;
    /**
    * @member {Array.<module:model/ApplicationToInstall>} applicationsToInstall
    */
    'applicationsToInstall' = undefined;
    /**
    * @member {Boolean} connectToInternet
    */
    'connectToInternet' = undefined;
    /**
    * @member {module:model/Limits} limits
    */
    'limits' = undefined;




}
