/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Limits from './Limits';

/**
* The Body model module.
* @module model/Body
* @version 1.0
*/
export default class Body {
    /**
    * Constructs a new <code>Body</code>.
    * @alias module:model/Body
    * @class
    * @param name {String} 
    * @param autostart {Boolean} 
    * @param applicationToInstall {Array.<String>} 
    */

    constructor(name, autostart, applicationToInstall) {
        
        
        this['name'] = name;
        this['autostart'] = autostart;
        this['applicationToInstall'] = applicationToInstall;
        
    }

    /**
    * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body} obj Optional instance to populate.
    * @return {module:model/Body} The populated <code>Body</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('autostart')) {
                obj['autostart'] = ApiClient.convertToType(data['autostart'], 'Boolean');
            }
            if (data.hasOwnProperty('templateId')) {
                obj['templateId'] = ApiClient.convertToType(data['templateId'], 'Number');
            }
            if (data.hasOwnProperty('applicationToInstall')) {
                obj['applicationToInstall'] = ApiClient.convertToType(data['applicationToInstall'], ['String']);
            }
            if (data.hasOwnProperty('customLimits')) {
                obj['customLimits'] = Limits.constructFromObject(data['customLimits']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {Boolean} autostart
    */
    'autostart' = undefined;
    /**
    * @member {Number} templateId
    */
    'templateId' = undefined;
    /**
    * @member {Array.<String>} applicationToInstall
    */
    'applicationToInstall' = undefined;
    /**
    * @member {module:model/Limits} customLimits
    */
    'customLimits' = undefined;




}
