/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Limits from './Limits';
import Snapshot from './Snapshot';
import Template from './Template';

/**
* The ContainerInfo model module.
* @module model/ContainerInfo
* @version 1.0
*/
export default class ContainerInfo {
    /**
    * Constructs a new <code>ContainerInfo</code>.
    * LXD container info
    * @alias module:model/ContainerInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerInfo} obj Optional instance to populate.
    * @return {module:model/ContainerInfo} The populated <code>ContainerInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerInfo();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = Template.constructFromObject(data['template']);
            }
            if (data.hasOwnProperty('ipv4')) {
                obj['ipv4'] = ApiClient.convertToType(data['ipv4'], 'String');
            }
            if (data.hasOwnProperty('ipv6')) {
                obj['ipv6'] = ApiClient.convertToType(data['ipv6'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('lastStartedOn')) {
                obj['lastStartedOn'] = ApiClient.convertToType(data['lastStartedOn'], 'String');
            }
            if (data.hasOwnProperty('stateful')) {
                obj['stateful'] = ApiClient.convertToType(data['stateful'], 'Boolean');
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('maxResources')) {
                obj['maxResources'] = Limits.constructFromObject(data['maxResources']);
            }
            if (data.hasOwnProperty('snapshots')) {
                obj['snapshots'] = ApiClient.convertToType(data['snapshots'], [Snapshot]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {module:model/Template} template
    */
    'template' = undefined;
    /**
    * @member {String} ipv4
    */
    'ipv4' = undefined;
    /**
    * @member {String} ipv6
    */
    'ipv6' = undefined;
    /**
    * Date and time of the creation of the container
    * @member {String} createdOn
    */
    'createdOn' = undefined;
    /**
    * Date and time when container was last started
    * @member {String} lastStartedOn
    */
    'lastStartedOn' = undefined;
    /**
    * true if container should store its state on stop and restore it on start
    * @member {Boolean} stateful
    */
    'stateful' = undefined;
    /**
    * @member {Number} statusCode
    */
    'statusCode' = undefined;
    /**
    * @member {module:model/Limits} maxResources
    */
    'maxResources' = undefined;
    /**
    * @member {Array.<module:model/Snapshot>} snapshots
    */
    'snapshots' = undefined;




}
