/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerResourceState from './ContainerResourceState';
import LightResourceState from './LightResourceState';

/**
* The ContainerState model module.
* @module model/ContainerState
* @version 1.0
*/
export default class ContainerState {
    /**
    * Constructs a new <code>ContainerState</code>.
    * LXD container state
    * @alias module:model/ContainerState
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerState} obj Optional instance to populate.
    * @return {module:model/ContainerState} The populated <code>ContainerState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerState();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('currentState')) {
                obj['currentState'] = ContainerResourceState.constructFromObject(data['currentState']);
            }
            if (data.hasOwnProperty('stateHistory')) {
                obj['stateHistory'] = ApiClient.convertToType(data['stateHistory'], [LightResourceState]);
            }
        }
        return obj;
    }

    /**
    * id of the container
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {module:model/ContainerResourceState} currentState
    */
    'currentState' = undefined;
    /**
    * history of states - 0 index = 10 min ago
    * @member {Array.<module:model/LightResourceState>} stateHistory
    */
    'stateHistory' = undefined;




}
