/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerResourceState from './ContainerResourceState';
import Snapshot from './Snapshot';
import Template from './Template';

/**
* The Container model module.
* @module model/Container
* @version 1.0
*/
export default class Container {
    /**
    * Constructs a new <code>Container</code>.
    * LXD container with info and state
    * @alias module:model/Container
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Container</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Container} obj Optional instance to populate.
    * @return {module:model/Container} The populated <code>Container</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Container();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = Template.constructFromObject(data['template']);
            }
            if (data.hasOwnProperty('stateful')) {
                obj['stateful'] = ApiClient.convertToType(data['stateful'], 'Boolean');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('lastStartedOn')) {
                obj['lastStartedOn'] = ApiClient.convertToType(data['lastStartedOn'], 'String');
            }
            if (data.hasOwnProperty('snapshots')) {
                obj['snapshots'] = ApiClient.convertToType(data['snapshots'], [Snapshot]);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ContainerResourceState.constructFromObject(data['state']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} url
    */
    'url' = undefined;
    /**
    * @member {module:model/Template} template
    */
    'template' = undefined;
    /**
    * @member {Boolean} stateful
    */
    'stateful' = undefined;
    /**
    * Date and time of the creation of the container
    * @member {String} createdOn
    */
    'createdOn' = undefined;
    /**
    * Date and time when container was last started
    * @member {String} lastStartedOn
    */
    'lastStartedOn' = undefined;
    /**
    * @member {Array.<module:model/Snapshot>} snapshots
    */
    'snapshots' = undefined;
    /**
    * @member {module:model/ContainerResourceState} state
    */
    'state' = undefined;




}
