/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ContainerResourceStateCPU model module.
* @module model/ContainerResourceStateCPU
* @version 1.0
*/
export default class ContainerResourceStateCPU {
    /**
    * Constructs a new <code>ContainerResourceStateCPU</code>.
    * @alias module:model/ContainerResourceStateCPU
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerResourceStateCPU</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceStateCPU} obj Optional instance to populate.
    * @return {module:model/ContainerResourceStateCPU} The populated <code>ContainerResourceStateCPU</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceStateCPU();
                        
            
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('usedTime')) {
                obj['usedTime'] = ApiClient.convertToType(data['usedTime'], 'Number');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * CPU limit in Hz
    * @member {Number} limit
    */
    'limit' = undefined;
    /**
    * Time used by the CPU in nanoseconds from the container start
    * @member {Number} usedTime
    */
    'usedTime' = undefined;
    /**
    * Used Hz in measured time
    * @member {Number} usage
    */
    'usage' = undefined;




}
