/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerResourceState from './ContainerResourceState';

/**
* The ContainerStateWithHistory model module.
* @module model/ContainerStateWithHistory
* @version 1.0
*/
export default class ContainerStateWithHistory {
    /**
    * Constructs a new <code>ContainerStateWithHistory</code>.
    * LXD container state containing current state and also the history of states
    * @alias module:model/ContainerStateWithHistory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerStateWithHistory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerStateWithHistory} obj Optional instance to populate.
    * @return {module:model/ContainerStateWithHistory} The populated <code>ContainerStateWithHistory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerStateWithHistory();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('stateHistory')) {
                obj['stateHistory'] = ApiClient.convertToType(data['stateHistory'], [ContainerResourceState]);
            }
        }
        return obj;
    }

    /**
    * id of the container
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * history of states - index 0 = current state, index 1 = pre-last state, n-1 = last remembered state.
    * @member {Array.<module:model/ContainerResourceState>} stateHistory
    */
    'stateHistory' = undefined;




}
