/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Limits from './Limits';
import ResourceState from './ResourceState';

/**
* The ContainerState model module.
* @module model/ContainerState
* @version 1.0
*/
export default class ContainerState {
    /**
    * Constructs a new <code>ContainerState</code>.
    * LXD container state
    * @alias module:model/ContainerState
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerState} obj Optional instance to populate.
    * @return {module:model/ContainerState} The populated <code>ContainerState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerState();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('maxResources')) {
                obj['maxResources'] = Limits.constructFromObject(data['maxResources']);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ResourceState.constructFromObject(data['state']);
            }
        }
        return obj;
    }

    /**
    * id of the container
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {module:model/Limits} maxResources
    */
    'maxResources' = undefined;
    /**
    * @member {module:model/ResourceState} state
    */
    'state' = undefined;




}
