/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerResourceStateInner from './ContainerResourceStateInner';

/**
* The ContainerResourceState model module.
* @module model/ContainerResourceState
* @version 1.0
*/
export default class ContainerResourceState extends Array {
    /**
    * Constructs a new <code>ContainerResourceState</code>.
    * Usage of resources assigned to container in time arrayIndex * 10 minutes (0 &#x3D; last measurment)
    * @alias module:model/ContainerResourceState
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>ContainerResourceState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceState} obj Optional instance to populate.
    * @return {module:model/ContainerResourceState} The populated <code>ContainerResourceState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceState();
            ApiClient.constructFromObject(data, obj, 'ContainerResourceStateInner');
            
            
        }
        return obj;
    }





}
