/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerResourceStateAdresses from './ContainerResourceStateAdresses';
import ContainerResourceStateCounters from './ContainerResourceStateCounters';

/**
* The ContainerResourceStateNetworks model module.
* @module model/ContainerResourceStateNetworks
* @version 1.0
*/
export default class ContainerResourceStateNetworks {
    /**
    * Constructs a new <code>ContainerResourceStateNetworks</code>.
    * @alias module:model/ContainerResourceStateNetworks
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerResourceStateNetworks</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceStateNetworks} obj Optional instance to populate.
    * @return {module:model/ContainerResourceStateNetworks} The populated <code>ContainerResourceStateNetworks</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceStateNetworks();
                        
            
            if (data.hasOwnProperty('networkName')) {
                obj['networkName'] = ApiClient.convertToType(data['networkName'], 'String');
            }
            if (data.hasOwnProperty('adresses')) {
                obj['adresses'] = ApiClient.convertToType(data['adresses'], [ContainerResourceStateAdresses]);
            }
            if (data.hasOwnProperty('counters')) {
                obj['counters'] = ContainerResourceStateCounters.constructFromObject(data['counters']);
            }
            if (data.hasOwnProperty('hwaddr')) {
                obj['hwaddr'] = ApiClient.convertToType(data['hwaddr'], 'String');
            }
            if (data.hasOwnProperty('hostName')) {
                obj['hostName'] = ApiClient.convertToType(data['hostName'], 'String');
            }
            if (data.hasOwnProperty('mtu')) {
                obj['mtu'] = ApiClient.convertToType(data['mtu'], 'Number');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} networkName
    */
    'networkName' = undefined;
    /**
    * @member {Array.<module:model/ContainerResourceStateAdresses>} adresses
    */
    'adresses' = undefined;
    /**
    * @member {module:model/ContainerResourceStateCounters} counters
    */
    'counters' = undefined;
    /**
    * @member {String} hwaddr
    */
    'hwaddr' = undefined;
    /**
    * @member {String} hostName
    */
    'hostName' = undefined;
    /**
    * @member {Number} mtu
    */
    'mtu' = undefined;
    /**
    * @member {String} state
    */
    'state' = undefined;
    /**
    * @member {String} type
    */
    'type' = undefined;




}
