/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ContainerResourceStateCounters model module.
* @module model/ContainerResourceStateCounters
* @version 1.0
*/
export default class ContainerResourceStateCounters {
    /**
    * Constructs a new <code>ContainerResourceStateCounters</code>.
    * @alias module:model/ContainerResourceStateCounters
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerResourceStateCounters</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceStateCounters} obj Optional instance to populate.
    * @return {module:model/ContainerResourceStateCounters} The populated <code>ContainerResourceStateCounters</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceStateCounters();
                        
            
            if (data.hasOwnProperty('downloadBandwidthUsage')) {
                obj['downloadBandwidthUsage'] = ApiClient.convertToType(data['downloadBandwidthUsage'], 'Number');
            }
            if (data.hasOwnProperty('downloadSpeed')) {
                obj['downloadSpeed'] = ApiClient.convertToType(data['downloadSpeed'], 'Number');
            }
            if (data.hasOwnProperty('uploadBandwidthUsage')) {
                obj['uploadBandwidthUsage'] = ApiClient.convertToType(data['uploadBandwidthUsage'], 'Number');
            }
            if (data.hasOwnProperty('uploadSpeed')) {
                obj['uploadSpeed'] = ApiClient.convertToType(data['uploadSpeed'], 'Number');
            }
        }
        return obj;
    }

    /**
    * usage of download bandwidth in percent
    * @member {Number} downloadBandwidthUsage
    */
    'downloadBandwidthUsage' = undefined;
    /**
    * number of bytes that were downloaded in bits/s
    * @member {Number} downloadSpeed
    */
    'downloadSpeed' = undefined;
    /**
    * usage of upload bandwidth in percent
    * @member {Number} uploadBandwidthUsage
    */
    'uploadBandwidthUsage' = undefined;
    /**
    * number of bytes that were uploaded in bits/s
    * @member {Number} uploadSpeed
    */
    'uploadSpeed' = undefined;




}
