/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ContainerResourceStateRAM model module.
* @module model/ContainerResourceStateRAM
* @version 1.0
*/
export default class ContainerResourceStateRAM {
    /**
    * Constructs a new <code>ContainerResourceStateRAM</code>.
    * @alias module:model/ContainerResourceStateRAM
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerResourceStateRAM</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceStateRAM} obj Optional instance to populate.
    * @return {module:model/ContainerResourceStateRAM} The populated <code>ContainerResourceStateRAM</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceStateRAM();
                        
            
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
            if (data.hasOwnProperty('usagePeak')) {
                obj['usagePeak'] = ApiClient.convertToType(data['usagePeak'], 'Number');
            }
            if (data.hasOwnProperty('percentConsumed')) {
                obj['percentConsumed'] = ApiClient.convertToType(data['percentConsumed'], 'Number');
            }
        }
        return obj;
    }

    /**
    * last measured RAM usage in Bytes
    * @member {Number} usage
    */
    'usage' = undefined;
    /**
    * maximum measured RAM usage in Bytes
    * @member {Number} usagePeak
    */
    'usagePeak' = undefined;
    /**
    * Percentage of RAM allocated from the overall RAM available
    * @member {Number} percentConsumed
    */
    'percentConsumed' = undefined;




}
