/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ContainerResourceStateDiskDevices model module.
* @module model/ContainerResourceStateDiskDevices
* @version 1.0
*/
export default class ContainerResourceStateDiskDevices {
    /**
    * Constructs a new <code>ContainerResourceStateDiskDevices</code>.
    * @alias module:model/ContainerResourceStateDiskDevices
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContainerResourceStateDiskDevices</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContainerResourceStateDiskDevices} obj Optional instance to populate.
    * @return {module:model/ContainerResourceStateDiskDevices} The populated <code>ContainerResourceStateDiskDevices</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerResourceStateDiskDevices();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Name of the device (disk) e.g. root
    * @member {String} name
    */
    'name' = undefined;
    /**
    * current disk usage in bytes
    * @member {Number} usage
    */
    'usage' = undefined;




}
