/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationToInstall from './ApplicationToInstall';
import Template from './Template';

/**
* The CreateContainerData model module.
* @module model/CreateContainerData
* @version 1.0
*/
export default class CreateContainerData {
    /**
    * Constructs a new <code>CreateContainerData</code>.
    * All the data necessary to create a container (except for projects and resources - this has to be achieved via different ways)
    * @alias module:model/CreateContainerData
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateContainerData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateContainerData} obj Optional instance to populate.
    * @return {module:model/CreateContainerData} The populated <code>CreateContainerData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateContainerData();
                        
            
            if (data.hasOwnProperty('templateTypes')) {
                obj['templateTypes'] = ApiClient.convertToType(data['templateTypes'], [Template]);
            }
            if (data.hasOwnProperty('applicationsToInstall')) {
                obj['applicationsToInstall'] = ApiClient.convertToType(data['applicationsToInstall'], [ApplicationToInstall]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Template>} templateTypes
    */
    'templateTypes' = undefined;
    /**
    * @member {Array.<module:model/ApplicationToInstall>} applicationsToInstall
    */
    'applicationsToInstall' = undefined;




}
