/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationToInstall from './ApplicationToInstall';
import Template from './Template';

/**
* The CreateInstanceConfigData model module.
* @module model/CreateInstanceConfigData
* @version 1.0
*/
export default class CreateInstanceConfigData {
    /**
    * Constructs a new <code>CreateInstanceConfigData</code>.
    * @alias module:model/CreateInstanceConfigData
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CreateInstanceConfigData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateInstanceConfigData} obj Optional instance to populate.
    * @return {module:model/CreateInstanceConfigData} The populated <code>CreateInstanceConfigData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateInstanceConfigData();
                        
            
            if (data.hasOwnProperty('templates')) {
                obj['templates'] = ApiClient.convertToType(data['templates'], [Template]);
            }
            if (data.hasOwnProperty('applicationsToInstall')) {
                obj['applicationsToInstall'] = ApiClient.convertToType(data['applicationsToInstall'], [ApplicationToInstall]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Template>} templates
    */
    'templates' = undefined;
    /**
    * @member {Array.<module:model/ApplicationToInstall>} applicationsToInstall
    */
    'applicationsToInstall' = undefined;




}
