/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The HostInformationCPU model module.
* @module model/HostInformationCPU
* @version 1.0
*/
export default class HostInformationCPU {
    /**
    * Constructs a new <code>HostInformationCPU</code>.
    * @alias module:model/HostInformationCPU
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HostInformationCPU</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HostInformationCPU} obj Optional instance to populate.
    * @return {module:model/HostInformationCPU} The populated <code>HostInformationCPU</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HostInformationCPU();
                        
            
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'Number');
            }
        }
        return obj;
    }

    /**
    * e.g. Intel Core i3 1005G1 Ice Lake
    * @member {String} model
    */
    'model' = undefined;
    /**
    * frequency in MHz
    * @member {Number} frequency
    */
    'frequency' = undefined;




}
