/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LightResourceStateNetworkUpload model module.
* @module model/LightResourceStateNetworkUpload
* @version 1.0
*/
export default class LightResourceStateNetworkUpload {
    /**
    * Constructs a new <code>LightResourceStateNetworkUpload</code>.
    * @alias module:model/LightResourceStateNetworkUpload
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LightResourceStateNetworkUpload</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LightResourceStateNetworkUpload} obj Optional instance to populate.
    * @return {module:model/LightResourceStateNetworkUpload} The populated <code>LightResourceStateNetworkUpload</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightResourceStateNetworkUpload();
                        
            
            if (data.hasOwnProperty('uploadSpeed')) {
                obj['uploadSpeed'] = ApiClient.convertToType(data['uploadSpeed'], 'Number');
            }
            if (data.hasOwnProperty('uploadBandwidthUsage')) {
                obj['uploadBandwidthUsage'] = ApiClient.convertToType(data['uploadBandwidthUsage'], 'Number');
            }
            if (data.hasOwnProperty('allocatedUploadSpeed')) {
                obj['allocatedUploadSpeed'] = ApiClient.convertToType(data['allocatedUploadSpeed'], 'Number');
            }
            if (data.hasOwnProperty('allocatedBandwidthUsage')) {
                obj['allocatedBandwidthUsage'] = ApiClient.convertToType(data['allocatedBandwidthUsage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * last recorded upload speed in bits/s in connection to the internet
    * @member {Number} uploadSpeed
    */
    'uploadSpeed' = undefined;
    /**
    * usage of upload bandwidth in percent in connection to the internet
    * @member {Number} uploadBandwidthUsage
    */
    'uploadBandwidthUsage' = undefined;
    /**
    * last recorded allocated upload speed in bits/s in connection to the internet (sum of container limits - upload speed)
    * @member {Number} allocatedUploadSpeed
    */
    'allocatedUploadSpeed' = undefined;
    /**
    * usage of upload bandwidth in percent in connection to the internet
    * @member {Number} allocatedBandwidthUsage
    */
    'allocatedBandwidthUsage' = undefined;




}
