/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LightResourceStateDisk model module.
* @module model/LightResourceStateDisk
* @version 1.0
*/
export default class LightResourceStateDisk {
    /**
    * Constructs a new <code>LightResourceStateDisk</code>.
    * @alias module:model/LightResourceStateDisk
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LightResourceStateDisk</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LightResourceStateDisk} obj Optional instance to populate.
    * @return {module:model/LightResourceStateDisk} The populated <code>LightResourceStateDisk</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightResourceStateDisk();
                        
            
            if (data.hasOwnProperty('currentlyConsumedMemory')) {
                obj['currentlyConsumedMemory'] = ApiClient.convertToType(data['currentlyConsumedMemory'], 'Number');
            }
            if (data.hasOwnProperty('percentConsumed')) {
                obj['percentConsumed'] = ApiClient.convertToType(data['percentConsumed'], 'Number');
            }
        }
        return obj;
    }

    /**
    * current disk usage in bytes
    * @member {Number} currentlyConsumedMemory
    */
    'currentlyConsumedMemory' = undefined;
    /**
    * Percentage of the allocated disk memory from the overall memory available
    * @member {Number} percentConsumed
    */
    'percentConsumed' = undefined;




}
