/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LightResourceStateRAM model module.
* @module model/LightResourceStateRAM
* @version 1.0
*/
export default class LightResourceStateRAM {
    /**
    * Constructs a new <code>LightResourceStateRAM</code>.
    * @alias module:model/LightResourceStateRAM
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LightResourceStateRAM</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LightResourceStateRAM} obj Optional instance to populate.
    * @return {module:model/LightResourceStateRAM} The populated <code>LightResourceStateRAM</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightResourceStateRAM();
                        
            
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
            if (data.hasOwnProperty('percentConsumed')) {
                obj['percentConsumed'] = ApiClient.convertToType(data['percentConsumed'], 'Number');
            }
        }
        return obj;
    }

    /**
    * last measured RAM usage in Bytes
    * @member {Number} usage
    */
    'usage' = undefined;
    /**
    * Percentage of RAM allocated from the overall RAM available
    * @member {Number} percentConsumed
    */
    'percentConsumed' = undefined;




}
