/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LightResourceStateNetwork model module.
* @module model/LightResourceStateNetwork
* @version 1.0
*/
export default class LightResourceStateNetwork {
    /**
    * Constructs a new <code>LightResourceStateNetwork</code>.
    * @alias module:model/LightResourceStateNetwork
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LightResourceStateNetwork</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LightResourceStateNetwork} obj Optional instance to populate.
    * @return {module:model/LightResourceStateNetwork} The populated <code>LightResourceStateNetwork</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightResourceStateNetwork();
                        
            
            if (data.hasOwnProperty('bytesSent')) {
                obj['bytesSent'] = ApiClient.convertToType(data['bytesSent'], 'Number');
            }
            if (data.hasOwnProperty('uploadBandwidthUsage')) {
                obj['uploadBandwidthUsage'] = ApiClient.convertToType(data['uploadBandwidthUsage'], 'Number');
            }
            if (data.hasOwnProperty('bytesReceived')) {
                obj['bytesReceived'] = ApiClient.convertToType(data['bytesReceived'], 'Number');
            }
            if (data.hasOwnProperty('downloadBandwidthUsage')) {
                obj['downloadBandwidthUsage'] = ApiClient.convertToType(data['downloadBandwidthUsage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * last recorded upload in bytes/s
    * @member {Number} bytesSent
    */
    'bytesSent' = undefined;
    /**
    * usage of upload bandwidth in percent
    * @member {Number} uploadBandwidthUsage
    */
    'uploadBandwidthUsage' = undefined;
    /**
    * last recorded download in bytes/s
    * @member {Number} bytesReceived
    */
    'bytesReceived' = undefined;
    /**
    * usage of download bandwidth in percent
    * @member {Number} downloadBandwidthUsage
    */
    'downloadBandwidthUsage' = undefined;




}
