/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LightResourceStateNetworkDownload from './LightResourceStateNetworkDownload';
import LightResourceStateNetworkUpload from './LightResourceStateNetworkUpload';

/**
* The LightResourceStateNetwork model module.
* @module model/LightResourceStateNetwork
* @version 1.0
*/
export default class LightResourceStateNetwork {
    /**
    * Constructs a new <code>LightResourceStateNetwork</code>.
    * @alias module:model/LightResourceStateNetwork
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LightResourceStateNetwork</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LightResourceStateNetwork} obj Optional instance to populate.
    * @return {module:model/LightResourceStateNetwork} The populated <code>LightResourceStateNetwork</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightResourceStateNetwork();
                        
            
            if (data.hasOwnProperty('upload')) {
                obj['upload'] = LightResourceStateNetworkUpload.constructFromObject(data['upload']);
            }
            if (data.hasOwnProperty('download')) {
                obj['download'] = LightResourceStateNetworkDownload.constructFromObject(data['download']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/LightResourceStateNetworkUpload} upload
    */
    'upload' = undefined;
    /**
    * @member {module:model/LightResourceStateNetworkDownload} download
    */
    'download' = undefined;




}
