/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LimitsInternet model module.
* @module model/LimitsInternet
* @version 1.0
*/
export default class LimitsInternet {
    /**
    * Constructs a new <code>LimitsInternet</code>.
    * @alias module:model/LimitsInternet
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LimitsInternet</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LimitsInternet} obj Optional instance to populate.
    * @return {module:model/LimitsInternet} The populated <code>LimitsInternet</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LimitsInternet();
                        
            
            if (data.hasOwnProperty('download')) {
                obj['download'] = ApiClient.convertToType(data['download'], 'Number');
            }
            if (data.hasOwnProperty('upload')) {
                obj['upload'] = ApiClient.convertToType(data['upload'], 'Number');
            }
        }
        return obj;
    }

    /**
    * in bits/s
    * @member {Number} download
    */
    'download' = undefined;
    /**
    * in bits/s
    * @member {Number} upload
    */
    'upload' = undefined;




}
