/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworkStateCountersDownload from './NetworkStateCountersDownload';
import NetworkStateCountersUpload from './NetworkStateCountersUpload';

/**
* The NetworkStateCounters model module.
* @module model/NetworkStateCounters
* @version 1.0
*/
export default class NetworkStateCounters {
    /**
    * Constructs a new <code>NetworkStateCounters</code>.
    * @alias module:model/NetworkStateCounters
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworkStateCounters</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NetworkStateCounters} obj Optional instance to populate.
    * @return {module:model/NetworkStateCounters} The populated <code>NetworkStateCounters</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkStateCounters();
                        
            
            if (data.hasOwnProperty('download')) {
                obj['download'] = NetworkStateCountersDownload.constructFromObject(data['download']);
            }
            if (data.hasOwnProperty('upload')) {
                obj['upload'] = NetworkStateCountersUpload.constructFromObject(data['upload']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/NetworkStateCountersDownload} download
    */
    'download' = undefined;
    /**
    * @member {module:model/NetworkStateCountersUpload} upload
    */
    'upload' = undefined;




}
