/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NetworkStateCountersDownload model module.
* @module model/NetworkStateCountersDownload
* @version 1.0
*/
export default class NetworkStateCountersDownload {
    /**
    * Constructs a new <code>NetworkStateCountersDownload</code>.
    * @alias module:model/NetworkStateCountersDownload
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworkStateCountersDownload</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NetworkStateCountersDownload} obj Optional instance to populate.
    * @return {module:model/NetworkStateCountersDownload} The populated <code>NetworkStateCountersDownload</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkStateCountersDownload();
                        
            
            if (data.hasOwnProperty('usedSpeed')) {
                obj['usedSpeed'] = ApiClient.convertToType(data['usedSpeed'], 'Number');
            }
            if (data.hasOwnProperty('bytesFromStart')) {
                obj['bytesFromStart'] = ApiClient.convertToType(data['bytesFromStart'], 'Number');
            }
            if (data.hasOwnProperty('packetsFromStart')) {
                obj['packetsFromStart'] = ApiClient.convertToType(data['packetsFromStart'], 'Number');
            }
        }
        return obj;
    }

    /**
    * number of bytes that were downloaded/1s in bits/s
    * @member {Number} usedSpeed
    */
    'usedSpeed' = undefined;
    /**
    * number of bytes received from the beginning of the run of this container
    * @member {Number} bytesFromStart
    */
    'bytesFromStart' = undefined;
    /**
    * number of packets received from the beginning of the run of this container
    * @member {Number} packetsFromStart
    */
    'packetsFromStart' = undefined;




}
