/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerState from './ContainerState';
import LightResourceState from './LightResourceState';

/**
* The ProjectState model module.
* @module model/ProjectState
* @version 1.0
*/
export default class ProjectState {
    /**
    * Constructs a new <code>ProjectState</code>.
    * Object that knows state and history of project and all containers in it
    * @alias module:model/ProjectState
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ProjectState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProjectState} obj Optional instance to populate.
    * @return {module:model/ProjectState} The populated <code>ProjectState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectState();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('containersState')) {
                obj['containersState'] = ApiClient.convertToType(data['containersState'], [ContainerState]);
            }
            if (data.hasOwnProperty('projectState')) {
                obj['projectState'] = LightResourceState.constructFromObject(data['projectState']);
            }
            if (data.hasOwnProperty('stateHistory')) {
                obj['stateHistory'] = ApiClient.convertToType(data['stateHistory'], [LightResourceState]);
            }
        }
        return obj;
    }

    /**
    * id of the project
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Array.<module:model/ContainerState>} containersState
    */
    'containersState' = undefined;
    /**
    * @member {module:model/LightResourceState} projectState
    */
    'projectState' = undefined;
    /**
    * history of states - 0 index = 10 min ago
    * @member {Array.<module:model/LightResourceState>} stateHistory
    */
    'stateHistory' = undefined;




}
