/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerInfo from './ContainerInfo';
import Limits from './Limits';
import User from './User';

/**
* The ProjectInfo model module.
* @module model/ProjectInfo
* @version 1.0
*/
export default class ProjectInfo {
    /**
    * Constructs a new <code>ProjectInfo</code>.
    * @alias module:model/ProjectInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ProjectInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProjectInfo} obj Optional instance to populate.
    * @return {module:model/ProjectInfo} The populated <code>ProjectInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectInfo();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = User.constructFromObject(data['owner']);
            }
            if (data.hasOwnProperty('coworkers')) {
                obj['coworkers'] = ApiClient.convertToType(data['coworkers'], [User]);
            }
            if (data.hasOwnProperty('maxResources')) {
                obj['maxResources'] = Limits.constructFromObject(data['maxResources']);
            }
            if (data.hasOwnProperty('containersInfo')) {
                obj['containersInfo'] = ApiClient.convertToType(data['containersInfo'], [ContainerInfo]);
            }
        }
        return obj;
    }

    /**
    * id of the project
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {module:model/User} owner
    */
    'owner' = undefined;
    /**
    * @member {Array.<module:model/User>} coworkers
    */
    'coworkers' = undefined;
    /**
    * @member {module:model/Limits} maxResources
    */
    'maxResources' = undefined;
    /**
    * @member {Array.<module:model/ContainerInfo>} containersInfo
    */
    'containersInfo' = undefined;




}
