/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceStateInner from './ResourceStateInner';

/**
* The ResourceState model module.
* @module model/ResourceState
* @version 1.0
*/
export default class ResourceState extends Array {
    /**
    * Constructs a new <code>ResourceState</code>.
    * Usage of resources assigned to container in time arrayIndex * 10 minutes (0 &#x3D; last measurment)
    * @alias module:model/ResourceState
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>ResourceState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ResourceState} obj Optional instance to populate.
    * @return {module:model/ResourceState} The populated <code>ResourceState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceState();
            ApiClient.constructFromObject(data, obj, 'ResourceStateInner');
            
            
        }
        return obj;
    }





}
