/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Limits from './Limits';

/**
* The ResourceStateInner model module.
* @module model/ResourceStateInner
* @version 1.0
*/
export default class ResourceStateInner {
    /**
    * Constructs a new <code>ResourceStateInner</code>.
    * @alias module:model/ResourceStateInner
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ResourceStateInner</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ResourceStateInner} obj Optional instance to populate.
    * @return {module:model/ResourceStateInner} The populated <code>ResourceStateInner</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceStateInner();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = Limits.constructFromObject(data['limits']);
            }
            if (data.hasOwnProperty('CPU')) {
                obj['CPU'] = ApiClient.convertToType(data['CPU'], Object);
            }
            if (data.hasOwnProperty('RAM')) {
                obj['RAM'] = ApiClient.convertToType(data['RAM'], Object);
            }
            if (data.hasOwnProperty('disk')) {
                obj['disk'] = ApiClient.convertToType(data['disk'], Object);
            }
            if (data.hasOwnProperty('networks')) {
                obj['networks'] = ApiClient.convertToType(data['networks'], [Object]);
            }
            if (data.hasOwnProperty('numberOfProcesses')) {
                obj['numberOfProcesses'] = ApiClient.convertToType(data['numberOfProcesses'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {Number} statusCode
    */
    'statusCode' = undefined;
    /**
    * @member {module:model/Limits} limits
    */
    'limits' = undefined;
    /**
    * @member {Object} CPU
    */
    'CPU' = undefined;
    /**
    * @member {Object} RAM
    */
    'RAM' = undefined;
    /**
    * @member {Object} disk
    */
    'disk' = undefined;
    /**
    * @member {Array.<Object>} networks
    */
    'networks' = undefined;
    /**
    * Process count
    * @member {Number} numberOfProcesses
    */
    'numberOfProcesses' = undefined;




}
