/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Snapshot model module.
* @module model/Snapshot
* @version 1.0
*/
export default class Snapshot {
    /**
    * Constructs a new <code>Snapshot</code>.
    * @alias module:model/Snapshot
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Snapshot</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Snapshot} obj Optional instance to populate.
    * @return {module:model/Snapshot} The populated <code>Snapshot</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Snapshot();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
            if (data.hasOwnProperty('stateful')) {
                obj['stateful'] = ApiClient.convertToType(data['stateful'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Name of the snapshot
    * @member {String} name
    */
    'name' = undefined;
    /**
    * The time of creation
    * @member {String} timestamp
    */
    'timestamp' = undefined;
    /**
    * True if state of the container should be maintained
    * @member {Boolean} stateful
    */
    'stateful' = undefined;




}
