/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Image from './Image';

/**
* The Template model module.
* @module model/Template
* @version 1.0
*/
export default class Template {
    /**
    * Constructs a new <code>Template</code>.
    * Combination of image and configuration. User can then create instances of these templates
    * @alias module:model/Template
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Template</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Template} obj Optional instance to populate.
    * @return {module:model/Template} The populated <code>Template</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Template();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = Image.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('minDiskUsage')) {
                obj['minDiskUsage'] = ApiClient.convertToType(data['minDiskUsage'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Id of a template generatd by database
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} createdOn
    */
    'createdOn' = undefined;
    /**
    * @member {module:model/Image} image
    */
    'image' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * minimum disk space needed for the container to work in Bytes.
    * @member {Number} minDiskUsage
    */
    'minDiskUsage' = undefined;




}
