/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Limits from './Limits';
import ProjectInfo from './ProjectInfo';

/**
* The UserProjectsInfo model module.
* @module model/UserProjectsInfo
* @version 1.0
*/
export default class UserProjectsInfo {
    /**
    * Constructs a new <code>UserProjectsInfo</code>.
    * @alias module:model/UserProjectsInfo
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserProjectsInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserProjectsInfo} obj Optional instance to populate.
    * @return {module:model/UserProjectsInfo} The populated <code>UserProjectsInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProjectsInfo();
                        
            
            if (data.hasOwnProperty('maxResources')) {
                obj['maxResources'] = Limits.constructFromObject(data['maxResources']);
            }
            if (data.hasOwnProperty('projectsInfo')) {
                obj['projectsInfo'] = ApiClient.convertToType(data['projectsInfo'], [ProjectInfo]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Limits} maxResources
    */
    'maxResources' = undefined;
    /**
    * @member {Array.<module:model/ProjectInfo>} projectsInfo
    */
    'projectsInfo' = undefined;




}
