/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateContainerData from './CreateContainerData';
import HostInformation from './HostInformation';
import User from './User';
import UserProjects from './UserProjects';

/**
* The UserData model module.
* @module model/UserData
* @version 1.0
*/
export default class UserData {
    /**
    * Constructs a new <code>UserData</code>.
    * Object containing everything that is necessary for the user frontend to work
    * @alias module:model/UserData
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserData} obj Optional instance to populate.
    * @return {module:model/UserData} The populated <code>UserData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserData();
                        
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('userProjects')) {
                obj['userProjects'] = UserProjects.constructFromObject(data['userProjects']);
            }
            if (data.hasOwnProperty('createContainerData')) {
                obj['createContainerData'] = CreateContainerData.constructFromObject(data['createContainerData']);
            }
            if (data.hasOwnProperty('hostInformation')) {
                obj['hostInformation'] = HostInformation.constructFromObject(data['hostInformation']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/User} user
    */
    'user' = undefined;
    /**
    * @member {module:model/UserProjects} userProjects
    */
    'userProjects' = undefined;
    /**
    * @member {module:model/CreateContainerData} createContainerData
    */
    'createContainerData' = undefined;
    /**
    * @member {module:model/HostInformation} hostInformation
    */
    'hostInformation' = undefined;




}
