/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserDataHostInformationCPU from './UserDataHostInformationCPU';

/**
* The UserDataHostInformation model module.
* @module model/UserDataHostInformation
* @version 1.0
*/
export default class UserDataHostInformation {
    /**
    * Constructs a new <code>UserDataHostInformation</code>.
    * @alias module:model/UserDataHostInformation
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserDataHostInformation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserDataHostInformation} obj Optional instance to populate.
    * @return {module:model/UserDataHostInformation} The populated <code>UserDataHostInformation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDataHostInformation();
                        
            
            if (data.hasOwnProperty('CPU')) {
                obj['CPU'] = UserDataHostInformationCPU.constructFromObject(data['CPU']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UserDataHostInformationCPU} CPU
    */
    'CPU' = undefined;




}
