/**
 * User API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LightResourceState from './LightResourceState';
import ProjectState from './ProjectState';

/**
* The UserProjectsState model module.
* @module model/UserProjectsState
* @version 1.0
*/
export default class UserProjectsState {
    /**
    * Constructs a new <code>UserProjectsState</code>.
    * Object that knows state and history of all projects and all containers in them
    * @alias module:model/UserProjectsState
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserProjectsState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserProjectsState} obj Optional instance to populate.
    * @return {module:model/UserProjectsState} The populated <code>UserProjectsState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProjectsState();
                        
            
            if (data.hasOwnProperty('projectsState')) {
                obj['projectsState'] = ApiClient.convertToType(data['projectsState'], [ProjectState]);
            }
            if (data.hasOwnProperty('userState')) {
                obj['userState'] = LightResourceState.constructFromObject(data['userState']);
            }
            if (data.hasOwnProperty('stateHistory')) {
                obj['stateHistory'] = ApiClient.convertToType(data['stateHistory'], [LightResourceState]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/ProjectState>} projectsState
    */
    'projectsState' = undefined;
    /**
    * @member {module:model/LightResourceState} userState
    */
    'userState' = undefined;
    /**
    * history of states - 0 index = 10 min ago
    * @member {Array.<module:model/LightResourceState>} stateHistory
    */
    'stateHistory' = undefined;




}
